/**
 * Regression suite for the two-layer plan-status durability gap.
 *
 * Layer 1 (in-memory): session.taskWorkflowStates Map. Mutated by
 *   advanceTaskState. Sync, fast, used by gate checks. Lost on restart.
 * Layer 2 (durable):   plan.json task.status, projected to plan.md via
 *   derivePlanMarkdown. Mutated by savePlan/updateTaskStatus.
 *
 * The former compatibility bridge was an unsafe second durable writer. The
 * exact-task update_task_status transaction/WAL now owns terminal persistence;
 * advanceTaskStateAndPersist remains only for diagnostic intermediate state.
 *
 * What this file asserts:
 *   1. updateTaskStatus alone updates plan.json + plan.md (control).
 *   2. advanceTaskState alone is intentionally Layer-1-only (contract).
 *   3. advanceTaskStateAndPersist refuses coder/terminal boundaries and never
 *      writes plan projections.
 */

import { afterEach, beforeEach, describe, expect, it } from 'bun:test';
import {
	existsSync,
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import * as path from 'node:path';
import type { Plan } from '../src/config/plan-schema';
import { loadPlan, updateTaskStatus } from '../src/plan/manager';
import {
	advanceTaskState,
	advanceTaskStateAndPersist,
	resetSwarmState,
	startAgentSession,
	swarmState,
} from '../src/state';

let TEST_BASE_DIR: string;
const SWARM_ID = 'repro-swarm';
const TASK_ID = '1.1';

function makePlan(): Plan {
	return {
		schema_version: '1.0.0',
		title: 'Repro Plan',
		swarm: SWARM_ID,
		migration_status: 'native',
		current_phase: 1,
		phases: [
			{
				id: 1,
				name: 'Phase 1',
				status: 'pending',
				tasks: [
					{
						id: TASK_ID,
						phase: 1,
						status: 'pending',
						size: 'small',
						description: 'Repro task — should advance to completed',
						depends: [],
						files_touched: [],
					},
				],
			},
		],
	};
}

function writePlanJson(dir: string, plan: Plan): void {
	const swarmDir = path.join(dir, '.swarm');
	mkdirSync(swarmDir, { recursive: true });
	writeFileSync(
		path.join(swarmDir, 'plan.json'),
		JSON.stringify(plan, null, 2),
		'utf-8',
	);
}

function readPlanJson(dir: string): Plan {
	const raw = readFileSync(path.join(dir, '.swarm', 'plan.json'), 'utf-8');
	return JSON.parse(raw) as Plan;
}

function cleanup() {
	if (existsSync(TEST_BASE_DIR)) {
		rmSync(TEST_BASE_DIR, { recursive: true, force: true });
	}
	// resetSwarmState also clears the module-level rehydration cache that other
	// state-related test files may have populated; agentSessions.clear() alone
	// is not sufficient under cross-file test runs.
	resetSwarmState();
}

beforeEach(() => {
	resetSwarmState();
	TEST_BASE_DIR = mkdtempSync(path.join(tmpdir(), 'repro-plan-md-'));
});

afterEach(() => {
	cleanup();
});

describe('Plan persistence — control test (updateTaskStatus directly)', () => {
	it('updateTaskStatus DOES persist completed status to plan.json', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());

		await updateTaskStatus(TEST_BASE_DIR, TASK_ID, 'completed');

		const plan = readPlanJson(TEST_BASE_DIR);
		const task = plan.phases[0].tasks[0];
		expect(task.status).toBe('completed');
	});

	it('updateTaskStatus DOES update plan.md checkbox to [x]', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());

		await updateTaskStatus(TEST_BASE_DIR, TASK_ID, 'completed');

		const mdPath = path.join(TEST_BASE_DIR, '.swarm', 'plan.md');
		// plan.md is regenerated by savePlan inside updateTaskStatus
		expect(existsSync(mdPath)).toBe(true);
		const md = readFileSync(mdPath, 'utf-8');
		// Markdown checklist for the completed task should use [x]
		expect(md).toMatch(/- \[x\][^\n]*1\.1/);
	});
});

describe('Plan persistence — Layer 1 contract (advanceTaskState is in-memory only)', () => {
	// These tests document an intentional contract: the sync state machine
	// MUST NOT touch disk. Persistence is the bridge helper's job.
	it('advanceTaskState alone advances Layer 1 but does not touch plan.json', () => {
		writePlanJson(TEST_BASE_DIR, makePlan());

		const sessionId = 'layer1-session-json';
		startAgentSession(sessionId, 'architect', 7200000, undefined);
		const session = swarmState.agentSessions.get(sessionId);
		if (!session) throw new Error('session not created');

		advanceTaskState(session, TASK_ID, 'coder_delegated');
		advanceTaskState(session, TASK_ID, 'pre_check_passed');
		advanceTaskState(session, TASK_ID, 'reviewer_run');
		advanceTaskState(session, TASK_ID, 'tests_run');
		advanceTaskState(session, TASK_ID, 'complete');

		expect(session.taskWorkflowStates.get(TASK_ID)).toBe('complete');

		// Layer 2 must be untouched by the sync state machine.
		const plan = readPlanJson(TEST_BASE_DIR);
		expect(plan.phases[0].tasks[0].status).toBe('pending');
	});
});

describe('Plan persistence — legacy wrapper cannot write durable boundaries', () => {
	it('coder_delegated requires the exact-task central transaction', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());
		startAgentSession('legacy-coder', 'architect', 7200000, undefined);
		const session = swarmState.agentSessions.get('legacy-coder')!;

		await expect(
			advanceTaskStateAndPersist(
				session,
				TASK_ID,
				'coder_delegated',
				TEST_BASE_DIR,
			),
		).rejects.toThrow('TASK_WORKFLOW_CENTRAL_TRANSACTION_REQUIRED');

		expect(session.taskWorkflowStates.has(TASK_ID)).toBe(false);
		expect(readPlanJson(TEST_BASE_DIR).phases[0].tasks[0].status).toBe(
			'pending',
		);
	});

	it('complete requires the exact-task terminal WAL transaction', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());
		startAgentSession('legacy-complete', 'architect', 7200000, undefined);
		const session = swarmState.agentSessions.get('legacy-complete')!;
		session.taskWorkflowStates.set(TASK_ID, 'tests_run');

		await expect(
			advanceTaskStateAndPersist(session, TASK_ID, 'complete', TEST_BASE_DIR),
		).rejects.toThrow('TASK_WORKFLOW_CENTRAL_TRANSACTION_REQUIRED');

		expect(session.taskWorkflowStates.get(TASK_ID)).toBe('tests_run');
		expect(readPlanJson(TEST_BASE_DIR).phases[0].tasks[0].status).toBe(
			'pending',
		);
		expect(existsSync(path.join(TEST_BASE_DIR, '.swarm', 'plan.md'))).toBe(
			false,
		);
	});

	it('diagnostic intermediate states remain in memory only', async () => {
		const inProgress = makePlan();
		inProgress.phases[0].tasks[0].status = 'in_progress';
		writePlanJson(TEST_BASE_DIR, inProgress);
		startAgentSession('legacy-intermediate', 'architect', 7200000, undefined);
		const session = swarmState.agentSessions.get('legacy-intermediate')!;
		session.taskWorkflowStates.set(TASK_ID, 'coder_delegated');

		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'pre_check_passed',
			TEST_BASE_DIR,
		);
		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'reviewer_run',
			TEST_BASE_DIR,
		);
		await advanceTaskStateAndPersist(
			session,
			TASK_ID,
			'tests_run',
			TEST_BASE_DIR,
		);

		expect(session.taskWorkflowStates.get(TASK_ID)).toBe('tests_run');
		expect(readPlanJson(TEST_BASE_DIR).phases[0].tasks[0].status).toBe(
			'in_progress',
		);
	});
});

describe('Plan persistence — sanity check (loadPlan after hand-crafted plan.json)', () => {
	it('loadPlan returns the plan we wrote', async () => {
		writePlanJson(TEST_BASE_DIR, makePlan());
		const plan = await loadPlan(TEST_BASE_DIR);
		expect(plan).not.toBeNull();
		expect(plan?.phases[0].tasks[0].id).toBe(TASK_ID);
		expect(plan?.phases[0].tasks[0].status).toBe('pending');
	});
});
