/**
 * Skill-improver service — produces a proposal markdown reviewing accumulated
 * knowledge, generated skills, the spec, and the architect prompt. When an
 * LLM delegate is available the body is generated by the configured
 * skill_improver agent (issue #629). When no delegate is wired and the
 * `allow_deterministic_fallback` flag is true, a deterministic offline body
 * is written, clearly tagged.
 *
 * Quota policy:
 *   - Reservation happens BEFORE any network I/O.
 *   - If the delegate is undefined and fallback is disabled, no quota is
 *     reserved — we refuse early with `no_llm_client`.
 *   - If the delegate construction itself fails before any network call
 *     (extremely unlikely in practice), we release the quota.
 *   - Once `client.session.prompt` has begun, the slot stays consumed even
 *     on failure: a flaky model must not burn unbounded retries within a
 *     window.
 */

import { existsSync } from 'node:fs';
import { mkdir, readFile } from 'node:fs/promises';
import * as path from 'node:path';
import type { EnrichmentQuotaOptions } from '../hooks/knowledge-curator.js';
import {
	readKnowledge,
	resolveHiveKnowledgePath,
	resolveSwarmKnowledgePath,
	transactKnowledge,
} from '../hooks/knowledge-store.js';
import type {
	HiveKnowledgeEntry,
	KnowledgeEntryBase,
	SwarmKnowledgeEntry,
} from '../hooks/knowledge-types.js';
import {
	createSkillImproverLLMDelegate,
	type SkillImproverLLMDelegate,
} from '../hooks/skill-improver-llm-factory.js';
import {
	computeWriteApprovalHash,
	currentWriteAuthoritySatisfies,
	type WriteApprovalRequest,
} from '../security/write-authority.js';
import { hasActiveFullAuto } from '../state.js';
import { atomicWriteSwarmFile } from '../utils/atomic-write';
import { warn } from '../utils/logger.js';
import {
	type AutoApplyResult,
	autoApplyProposals,
	DEFAULT_SKILL_MIN_CONFIDENCE,
	DEFAULT_SKILL_MIN_CONFIRMATIONS,
	generateSkills,
	listSkills,
	parseDraftFrontmatter,
	regenerateSkill,
	retireSkill,
	selectCandidateEntries,
} from './skill-generator.js';
import {
	getQuotaState,
	type QuotaWindow,
	releaseQuota,
	reserveQuota,
} from './skill-improver-quota.js';
import {
	writeMotifProposals,
	writeSuccessMotifProposals,
} from './trajectory-cluster.js';
import { hardenUnactionableEntries } from './unactionable-hardening.js';

export interface SkillImproverConfigInput {
	enabled: boolean;
	model: string | null;
	fallback_models: string[];
	max_calls_per_day: number;
	trigger: 'manual' | 'scheduled';
	consolidation_interval_hours?: number;
	consolidation_max_calls_per_run?: number;
	targets: Array<'skills' | 'spec' | 'architect_prompt' | 'knowledge'>;
	write_mode: 'proposal' | 'draft_skills';
	require_user_approval: boolean;
	quota_window: QuotaWindow;
	allow_deterministic_fallback: boolean;
}

export type SkillImproverTarget =
	| 'skills'
	| 'spec'
	| 'architect_prompt'
	| 'knowledge';

export interface SkillImproveRequest {
	directory: string;
	config: SkillImproverConfigInput;
	targets?: SkillImproverTarget[];
	mode?: 'proposal' | 'draft_skills';
	maxCalls?: number;
	now?: Date;
	sessionId?: string;
	signal?: AbortSignal;
	/** Test-only seam: inject a delegate. When undefined, the service uses
	 *  createSkillImproverLLMDelegate(directory, sessionId) which returns
	 *  undefined unless swarmState.opencodeClient is wired. */
	delegate?: SkillImproverLLMDelegate;
	/** Dedicated quota for hardening quarantined knowledge entries. This is
	 *  separate from the skill_improver proposal quota above. */
	enrichmentQuota?: EnrichmentQuotaOptions;
	/** Validate generated draft skills when write_mode is draft_skills. */
	evaluateDrafts?: boolean;
	/** Consolidation callers stage proposals only and must never auto-apply. */
	allowAutoApply?: boolean;
	/** Exact approval-phase proposal body returned by a prior challenge. */
	approvedCandidateContent?: string;
}

export interface SkillImproveResult {
	ran: boolean;
	reason?: string;
	approvalRequired?: {
		request?: WriteApprovalRequest;
		command?: string;
		candidateContent?: string;
		candidateContentChars?: number;
		candidateContentTokenEstimate?: number;
		allowedPaths?: string[];
	};
	proposalPath?: string;
	source?: 'llm' | 'deterministic_fallback';
	quota: {
		date: string;
		calls_used: number;
		max_calls: number;
	};
	draftSkillsWritten?: Array<{
		slug: string;
		path: string;
		sourceKnowledgeIds: string[];
	}>;
	model?: string;
	/** Change 4 (Task 4.3): outcome of the unactionable-knowledge hardening pass. */
	unactionableHardening?: {
		hardened: number;
		retired: number;
		remaining: number;
	};
	/** Change 6 (Task 5.3): macro trajectory-motif proposals written this run. */
	macroMotifs?: {
		motifs: number;
		proposalsWritten: number;
		/** #1821 AC21: motifs suppressed by the cross-producer dedup ledger. */
		duplicatesSuppressed?: number;
	};
	/** #1234 Part 4: success workflow-motif proposals written this run. */
	successMotifs?: {
		motifs: number;
		proposalsWritten: number;
		/** #1821 AC21: motifs suppressed by the cross-producer dedup ledger. */
		duplicatesSuppressed?: number;
	};
	/** Issue #1477: self-healing reconciliation of stale active generated skills
	 *  (regenerate-or-retire). In proposal-only runs this is a dry run (the
	 *  `retired` list holds retire-candidates that were not actually mutated). */
	staleSkillReconciliation?: StaleSkillReconciliationResult;
	/** #1234 Part 3D: critic-gated auto-apply of proposals in full-auto mode. */
	autoApply?: AutoApplyResult;
}

function timestampSlug(d: Date): string {
	return d.toISOString().replace(/[:.]/g, '-');
}

export const SKILL_IMPROVER_APPROVAL_CANDIDATE_ID = 'skill_improve_request';
export const MAX_APPROVED_CANDIDATE_CONTENT_CHARS = 64_000;

interface SkillImproverDraftWrite {
	slug: string;
	path: string;
	content: string;
	sourceKnowledgeIds: string[];
	missingSourceKnowledgeIds?: string[];
}

interface SkillImproverDraftSourceStampTarget {
	knowledgePath: string;
	ids: string[];
	slug: string;
	draftGeneratedSkillPath: string;
	updatedAt: string;
}

interface SkillImproverWriteManifestV1 {
	kind: 'skill_improver_write_manifest';
	version: 1;
	writeMode: 'draft_skills';
	source: 'llm' | 'deterministic_fallback';
	model?: string;
	proposalContent: string;
	drafts: SkillImproverDraftWrite[];
	draftSourceStamps: SkillImproverDraftSourceStampTarget[];
}

export function buildSkillImproverApprovalRequest(input: {
	sessionId?: string;
	candidateContent: string;
	allowedPaths: string[];
	candidateId?: string;
	generation?: number;
}): WriteApprovalRequest | null {
	const sessionId = input.sessionId?.trim();
	if (!sessionId) return null;
	const normalizedPaths = [
		...new Set(input.allowedPaths.map((entry) => entry.trim())),
	]
		.filter((entry) => entry.length > 0)
		.sort();
	return {
		targetSessionId: sessionId,
		action: 'skill_improve',
		candidateId:
			input.candidateId?.trim() || SKILL_IMPROVER_APPROVAL_CANDIDATE_ID,
		candidateContentHash: computeWriteApprovalHash({
			candidateContent: input.candidateContent,
		}),
		allowedPathDigest: computeWriteApprovalHash({
			allowedPaths: normalizedPaths,
		}),
		generation: input.generation ?? 0,
	};
}

export interface PreparedSkillImproverApprovalCandidate {
	directory: string;
	now: Date;
	source: 'llm' | 'deterministic_fallback';
	model?: string;
	proposalPath: string;
	proposalContent: string;
	allowedPaths: string[];
	candidateContent: string;
	draftWrites: SkillImproverDraftWrite[];
	draftSourceStamps: SkillImproverDraftSourceStampTarget[];
	request: WriteApprovalRequest;
	quota: {
		date: string;
		calls_used: number;
		max_calls: number;
	};
	quotaWindow: QuotaWindow;
	maxCalls: number;
	maxCallsPerDay: number;
	released: boolean;
}

type SkillImproverApprovalPreparation =
	| { kind: 'result'; result: SkillImproveResult }
	| { kind: 'prepared'; prepared: PreparedSkillImproverApprovalCandidate };

function estimateTokenCount(content: string): number {
	return Math.max(1, Math.ceil(content.length / 4));
}

function toApprovalPath(directory: string, targetPath: string): string {
	const relative = path.relative(directory, targetPath).replace(/\\/g, '/');
	if (
		relative.length > 0 &&
		!relative.startsWith('..') &&
		!path.isAbsolute(relative)
	) {
		return relative;
	}
	return path.resolve(targetPath).replace(/\\/g, '/');
}

function resolveApprovedPath(directory: string, approvedPath: string): string {
	const normalized = approvedPath.replace(/\//g, path.sep);
	return path.isAbsolute(normalized)
		? normalized
		: path.resolve(directory, normalized);
}

function buildDraftSkillsWriteManifest(input: {
	source: 'llm' | 'deterministic_fallback';
	model?: string;
	proposalContent: string;
	drafts: SkillImproverDraftWrite[];
	draftSourceStamps: SkillImproverDraftSourceStampTarget[];
}): string {
	const manifest: SkillImproverWriteManifestV1 = {
		kind: 'skill_improver_write_manifest',
		version: 1,
		writeMode: 'draft_skills',
		source: input.source,
		...(input.model ? { model: input.model } : {}),
		proposalContent: input.proposalContent,
		drafts: input.drafts,
		draftSourceStamps: input.draftSourceStamps,
	};
	return `${JSON.stringify(manifest, null, 2)}\n`;
}

function parseDraftSkillsWriteManifest(
	content: string,
): SkillImproverWriteManifestV1 | null {
	try {
		const parsed = JSON.parse(content) as unknown;
		if (!parsed || typeof parsed !== 'object') return null;
		const manifest = parsed as Record<string, unknown>;
		if (
			manifest.kind !== 'skill_improver_write_manifest' ||
			manifest.version !== 1 ||
			manifest.writeMode !== 'draft_skills' ||
			typeof manifest.proposalContent !== 'string' ||
			(manifest.source !== 'llm' &&
				manifest.source !== 'deterministic_fallback') ||
			!Array.isArray(manifest.drafts) ||
			!Array.isArray(manifest.draftSourceStamps)
		) {
			return null;
		}
		const drafts: SkillImproverDraftWrite[] = [];
		for (const entry of manifest.drafts) {
			if (!entry || typeof entry !== 'object') return null;
			const draft = entry as Record<string, unknown>;
			if (
				typeof draft.slug !== 'string' ||
				typeof draft.path !== 'string' ||
				typeof draft.content !== 'string' ||
				!Array.isArray(draft.sourceKnowledgeIds) ||
				!draft.sourceKnowledgeIds.every((id) => typeof id === 'string') ||
				(draft.missingSourceKnowledgeIds !== undefined &&
					(!Array.isArray(draft.missingSourceKnowledgeIds) ||
						!draft.missingSourceKnowledgeIds.every(
							(id) => typeof id === 'string',
						)))
			) {
				return null;
			}
			drafts.push({
				slug: draft.slug,
				path: draft.path,
				content: draft.content,
				sourceKnowledgeIds: [...new Set(draft.sourceKnowledgeIds)],
				...(Array.isArray(draft.missingSourceKnowledgeIds)
					? {
							missingSourceKnowledgeIds: [
								...new Set(draft.missingSourceKnowledgeIds),
							],
						}
					: {}),
			});
		}
		const draftSourceStamps: SkillImproverDraftSourceStampTarget[] = [];
		for (const entry of manifest.draftSourceStamps) {
			if (!entry || typeof entry !== 'object') return null;
			const stamp = entry as Record<string, unknown>;
			if (
				typeof stamp.knowledgePath !== 'string' ||
				typeof stamp.slug !== 'string' ||
				typeof stamp.draftGeneratedSkillPath !== 'string' ||
				typeof stamp.updatedAt !== 'string' ||
				!Array.isArray(stamp.ids) ||
				!stamp.ids.every((id) => typeof id === 'string')
			) {
				return null;
			}
			draftSourceStamps.push({
				knowledgePath: stamp.knowledgePath,
				ids: [...new Set(stamp.ids)],
				slug: stamp.slug,
				draftGeneratedSkillPath: stamp.draftGeneratedSkillPath,
				updatedAt: stamp.updatedAt,
			});
		}
		return {
			kind: 'skill_improver_write_manifest',
			version: 1,
			writeMode: 'draft_skills',
			source: manifest.source,
			...(typeof manifest.model === 'string' ? { model: manifest.model } : {}),
			proposalContent: manifest.proposalContent,
			drafts,
			draftSourceStamps,
		};
	} catch {
		return null;
	}
}

async function buildDraftSourceStampTargets(
	directory: string,
	drafts: SkillImproverDraftWrite[],
	updatedAt: string,
): Promise<SkillImproverDraftSourceStampTarget[]> {
	if (drafts.length === 0) return [];
	const swarmPath = resolveSwarmKnowledgePath(directory);
	const swarmEntries = await readKnowledge<KnowledgeEntryBase>(swarmPath);
	const swarmIds = new Set(swarmEntries.map((entry) => entry.id));
	const targets: SkillImproverDraftSourceStampTarget[] = [];
	for (const draft of drafts) {
		const ids = draft.sourceKnowledgeIds.filter((id) => swarmIds.has(id));
		if (ids.length > 0) {
			targets.push({
				knowledgePath: swarmPath,
				ids,
				slug: draft.slug,
				draftGeneratedSkillPath: draft.path,
				updatedAt,
			});
		}
	}
	const hivePath = resolveHiveKnowledgePath();
	if (!existsSync(hivePath)) return targets;
	const hiveEntries = await readKnowledge<KnowledgeEntryBase>(hivePath);
	const hiveIds = new Set(hiveEntries.map((entry) => entry.id));
	for (const draft of drafts) {
		const ids = draft.sourceKnowledgeIds.filter((id) => hiveIds.has(id));
		if (ids.length > 0) {
			targets.push({
				knowledgePath: hivePath,
				ids,
				slug: draft.slug,
				draftGeneratedSkillPath: draft.path,
				updatedAt,
			});
		}
	}
	return targets;
}

async function preflightDraftSourceStampTargets(
	targets: SkillImproverDraftSourceStampTarget[],
): Promise<string | null> {
	for (const target of targets) {
		const entries = await readKnowledge<KnowledgeEntryBase>(
			target.knowledgePath,
		);
		const ids = new Set(entries.map((entry) => entry.id));
		const missing = target.ids.filter((id) => !ids.has(id));
		if (missing.length > 0) {
			return `skill_improver approval manifest is stale; missing source knowledge ids for ${target.slug}: ${missing.join(', ')}`;
		}
	}
	return null;
}

async function applyDraftSourceStampTargets(
	targets: SkillImproverDraftSourceStampTarget[],
): Promise<void> {
	for (const target of targets) {
		const expectedIds = new Set(target.ids);
		const matched = new Set<string>();
		await transactKnowledge<KnowledgeEntryBase>(
			target.knowledgePath,
			(entries) => {
				let changed = false;
				for (const entry of entries) {
					if (!expectedIds.has(entry.id)) continue;
					entry.draft_generated_skill_slug = target.slug;
					entry.draft_generated_skill_path = target.draftGeneratedSkillPath;
					entry.updated_at = target.updatedAt;
					matched.add(entry.id);
					changed = true;
				}
				return changed ? entries : null;
			},
		);
		if (matched.size !== expectedIds.size) {
			throw new Error(
				`skill_improver approval manifest is stale; source stamp set for ${target.slug} changed during apply`,
			);
		}
	}
}

function buildPreparedApprovalCandidate(input: {
	directory: string;
	now: Date;
	source: 'llm' | 'deterministic_fallback';
	model?: string;
	proposalContent: string;
	candidateContent: string;
	draftWrites?: SkillImproverDraftWrite[];
	draftSourceStamps?: SkillImproverDraftSourceStampTarget[];
	quota: SkillImproveResult['quota'];
	quotaWindow: QuotaWindow;
	maxCalls: number;
	maxCallsPerDay: number;
	released: boolean;
	sessionId?: string;
}): SkillImproverApprovalPreparation {
	const contentHash = computeWriteApprovalHash({
		candidateContent: input.candidateContent,
	});
	const proposalPath = path.join(
		input.directory,
		'.swarm',
		'skill-improver',
		'proposals',
		`${contentHash}.md`,
	);
	const draftWrites = input.draftWrites ?? [];
	const draftSourceStamps = input.draftSourceStamps ?? [];
	const allowedPaths = [
		toApprovalPath(input.directory, proposalPath),
		...draftWrites.map((draft) => draft.path),
		...draftSourceStamps.map((target) =>
			toApprovalPath(input.directory, target.knowledgePath),
		),
	];
	const normalizedAllowedPaths = [...new Set(allowedPaths)].sort();
	const approvalRequest = buildSkillImproverApprovalRequest({
		sessionId: input.sessionId,
		candidateContent: input.candidateContent,
		allowedPaths: normalizedAllowedPaths,
	});
	if (!approvalRequest) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason:
					'skill_improver requires a session-bound write approval; no sessionId was provided',
				quota: input.quota,
				approvalRequired: {},
			},
		};
	}
	return {
		kind: 'prepared',
		prepared: {
			directory: input.directory,
			now: input.now,
			source: input.source,
			model: input.model,
			proposalPath,
			proposalContent: input.proposalContent,
			allowedPaths: normalizedAllowedPaths,
			candidateContent: input.candidateContent,
			draftWrites,
			draftSourceStamps,
			request: approvalRequest,
			quota: input.quota,
			quotaWindow: input.quotaWindow,
			maxCalls: input.maxCalls,
			maxCallsPerDay: input.maxCallsPerDay,
			released: input.released,
		},
	};
}

function buildApprovalRequiredResult(args: {
	reason: string;
	quota: SkillImproveResult['quota'];
	prepared: PreparedSkillImproverApprovalCandidate;
}): SkillImproveResult {
	return {
		ran: false,
		reason: args.reason,
		quota: args.quota,
		approvalRequired: {
			request: args.prepared.request,
			candidateContent: args.prepared.candidateContent,
			candidateContentChars: args.prepared.candidateContent.length,
			candidateContentTokenEstimate: estimateTokenCount(
				args.prepared.candidateContent,
			),
			allowedPaths: args.prepared.allowedPaths,
		},
		source: args.prepared.source,
		model: args.prepared.model,
	};
}

/**
 * Canonical atomic write (issue #2035). Previously leaked its
 * `target.tmp-<pid>-<ts>` temp on failure; the canonical helper cleans its
 * own temp in `finally` and the old grammar stays registered for discovery.
 */
async function atomicWrite(p: string, content: string): Promise<void> {
	await mkdir(path.dirname(p), { recursive: true });
	await atomicWriteSwarmFile(p, content);
}

interface InventorySnapshot {
	knowledge: { swarm: number; hive: number; archived: number };
	skills: {
		proposals: number;
		active: number;
		stale: number;
		metadataReadable: number;
	};
	highConfidenceClusters: number;
	matureCandidates: KnowledgeEntryBase[];
	staleActiveSkills: Array<{ slug: string; reasons: string[] }>;
}

async function gatherInventory(directory: string): Promise<InventorySnapshot> {
	const swarm = await readKnowledge<SwarmKnowledgeEntry>(
		resolveSwarmKnowledgePath(directory),
	);
	const hivePath = resolveHiveKnowledgePath();
	const hive = existsSync(hivePath)
		? await readKnowledge<HiveKnowledgeEntry>(hivePath)
		: [];
	const archived = [...swarm, ...hive].filter(
		(e) => e.status === 'archived',
	).length;
	const skills = await listSkills(directory);
	const knowledgeById = new Map(
		[...swarm, ...hive].map((entry) => [entry.id, entry]),
	);
	const staleActiveSkills: Array<{ slug: string; reasons: string[] }> = [];
	let metadataReadable = 0;
	for (const skill of skills.active) {
		let content: string;
		try {
			content = await readFile(skill.path, 'utf-8');
		} catch {
			continue;
		}
		const fm = parseDraftFrontmatter(content);
		if (!fm) {
			// Detection blind spot (issue #1477): a SKILL.md with no parseable YAML
			// frontmatter was silently skipped and never surfaced as stale. Record a
			// distinct reason so reconciliation can act on it instead of ignoring it.
			staleActiveSkills.push({
				slug: skill.slug,
				reasons: ['unparseable_frontmatter'],
			});
			continue;
		}
		// Hand-authored compatibility shims (skill_origin: shim) are intentionally
		// not generated from knowledge entries — never flag or reconcile them.
		if (fm.skillOrigin === 'shim') continue;
		metadataReadable += 1;
		const reasons: string[] = [];
		if (fm.sourceKnowledgeIds.length === 0) {
			reasons.push('missing_source_knowledge_ids');
		}
		if (!fm.generatedAt) {
			reasons.push('missing_generated_at');
		} else {
			const generatedAtMs = Date.parse(fm.generatedAt);
			if (!Number.isFinite(generatedAtMs)) {
				reasons.push('invalid_generated_at');
			} else {
				for (const id of fm.sourceKnowledgeIds) {
					const source = knowledgeById.get(id);
					if (!source) {
						reasons.push(`missing_source:${id}`);
						continue;
					}
					const updatedAtMs = Date.parse(source.updated_at);
					if (Number.isFinite(updatedAtMs) && updatedAtMs > generatedAtMs) {
						reasons.push(`updated_after_generation:${id}`);
					}
				}
			}
		}
		if (reasons.length > 0) {
			staleActiveSkills.push({
				slug: skill.slug,
				reasons: reasons.slice(0, 6),
			});
		}
	}
	const matureCandidates = await selectCandidateEntries(directory, {
		minConfidence: DEFAULT_SKILL_MIN_CONFIDENCE,
		minConfirmations: DEFAULT_SKILL_MIN_CONFIRMATIONS,
	});
	return {
		knowledge: { swarm: swarm.length, hive: hive.length, archived },
		skills: {
			proposals: skills.proposals.length,
			active: skills.active.length,
			stale: staleActiveSkills.length,
			metadataReadable,
		},
		highConfidenceClusters: matureCandidates.length,
		matureCandidates,
		staleActiveSkills,
	};
}

function buildSystemPrompt(
	targets: SkillImproverTarget[],
	cfg: SkillImproverConfigInput,
): string {
	return `You are skill_improver. Targets: ${targets.join(', ')}. Mode: ${cfg.write_mode}.

Output a single complete markdown proposal under 6000 chars. Sections required:
1. ## Inventory snapshot
2. ## Repeated ignored or violated directives (cite knowledge ids)
3. ## Concrete recommendations
4. ## Optional cluster suggestions for new draft skills (slug, title, source ids, target agents) — leave empty if none qualify
5. ## Risks and known limitations

Do NOT propose direct source-code edits. Do NOT call any tools. Return only the markdown body.`;
}

function buildUserPrompt(inv: InventorySnapshot): string {
	const matureRows = inv.matureCandidates
		.slice(0, 25)
		.map(
			(e) =>
				`- ${e.id} | conf=${e.confidence.toFixed(2)} | ${e.category} | "${e.lesson.slice(0, 140).replace(/\n/g, ' ')}"`,
		)
		.join('\n');
	return `INVENTORY
swarm_entries: ${inv.knowledge.swarm}
hive_entries: ${inv.knowledge.hive}
archived: ${inv.knowledge.archived}
draft_skills: ${inv.skills.proposals}
active_skills: ${inv.skills.active}
active_skills_with_readable_metadata: ${inv.skills.metadataReadable}
stale_active_skills: ${inv.skills.stale}
mature_uncompiled_clusters: ${inv.highConfidenceClusters}

TOP MATURE CANDIDATES (first 25):
${matureRows || '(none)'}

STALE ACTIVE SKILLS (first 10):
${
	inv.staleActiveSkills
		.slice(0, 10)
		.map((s) => `- ${s.slug} | ${s.reasons.join(', ')}`)
		.join('\n') || '(none)'
}
`;
}

function isAbortError(err: unknown): boolean {
	return (
		err instanceof Error &&
		(err.name === 'AbortError' || err.message === 'skill_improver_aborted')
	);
}

function throwIfAborted(signal: AbortSignal | undefined): void {
	if (!signal?.aborted) return;
	const err = new Error('skill_improver_aborted');
	err.name = 'AbortError';
	throw err;
}

function buildDeterministicProposal(args: {
	targets: SkillImproverTarget[];
	inventory: InventorySnapshot;
	model: string | null;
	now: Date;
}): string {
	const lines: string[] = [];
	lines.push('---');
	lines.push('source: deterministic_fallback');
	lines.push(`generated_at: ${args.now.toISOString()}`);
	lines.push(`targets: [${args.targets.join(', ')}]`);
	lines.push(`model: ${args.model ?? '(none — deterministic body)'}`);
	lines.push('---');
	lines.push('');
	lines.push('# Skill Improvement Proposal (deterministic fallback)');
	lines.push('');
	lines.push(
		'> No OpenCode LLM client was available when this proposal was generated. The body below is a deterministic inventory summary, not an LLM-derived analysis. To produce a real LLM proposal, run `skill_improve` from a session where the OpenCode runtime has wired `swarmState.opencodeClient`, or set `skill_improver.allow_deterministic_fallback: false` to force a hard failure instead of this fallback.',
	);
	lines.push('');
	lines.push('## Inventory snapshot');
	lines.push(
		`- Knowledge entries: swarm=${args.inventory.knowledge.swarm}, hive=${args.inventory.knowledge.hive}, archived=${args.inventory.knowledge.archived}`,
	);
	lines.push(
		`- Generated skills: proposals=${args.inventory.skills.proposals}, active=${args.inventory.skills.active}`,
	);
	lines.push(
		`- Active skills with readable metadata: ${args.inventory.skills.metadataReadable} (stale=${args.inventory.skills.stale})`,
	);
	lines.push(
		`- High-confidence un-skill'd clusters: ${args.inventory.highConfidenceClusters}`,
	);
	if (args.inventory.staleActiveSkills.length > 0) {
		lines.push(
			`- Stale active skills: ${args.inventory.staleActiveSkills.map((s) => s.slug).join(', ')}`,
		);
	}
	lines.push('');
	lines.push('## Recommendations');
	if (args.inventory.highConfidenceClusters > 0) {
		lines.push(
			`- Run \`skill_generate { mode: "draft" }\` to emit ${args.inventory.highConfidenceClusters} draft SKILL.md proposal(s).`,
		);
	}
	if (args.targets.includes('architect_prompt')) {
		lines.push(
			'- Manually review architect prompt against current high-priority directives.',
		);
	}
	if (args.targets.includes('spec')) {
		lines.push('- Audit `.swarm/spec.md` for drift.');
	}
	if (args.targets.includes('knowledge')) {
		lines.push(
			'- Archive low-confidence (< 0.3) entries with applied_explicit_count == 0 and shown_count > 5.',
		);
	}
	lines.push('');
	return lines.join('\n');
}

function buildLLMProposalFrame(args: {
	body: string;
	targets: SkillImproverTarget[];
	model: string | null;
	now: Date;
}): string {
	const lines: string[] = [];
	lines.push('---');
	lines.push('source: llm');
	lines.push(`generated_at: ${args.now.toISOString()}`);
	lines.push(`targets: [${args.targets.join(', ')}]`);
	if (args.model) lines.push(`model: ${args.model}`);
	lines.push('---');
	lines.push('');
	lines.push(args.body.trim());
	lines.push('');
	return lines.join('\n');
}

export interface StaleSkillReconciliationResult {
	regenerated: string[];
	retired: string[];
	skipped: string[];
	checked: number;
}

/**
 * Self-healing reconciliation for active generated skills (issue #1477). Detects
 * skills that are stale — no parseable frontmatter, or no `source_knowledge_ids`
 * anchoring them to live knowledge — and either regenerates them from their
 * source entries or retires them when no live source remains. Hand-authored
 * shims (`skill_origin: shim`) are skipped. Deterministic: no LLM, no quota draw;
 * intended to run on the skill_improver cadence. Fail-open per skill — one bad
 * skill never aborts the sweep.
 */
export async function reconcileStaleActiveSkills(
	directory: string,
	options: { dryRun?: boolean } = {},
): Promise<StaleSkillReconciliationResult> {
	const result: StaleSkillReconciliationResult = {
		regenerated: [],
		retired: [],
		skipped: [],
		checked: 0,
	};
	let skills: Awaited<ReturnType<typeof listSkills>>;
	try {
		skills = await listSkills(directory);
	} catch {
		return result;
	}
	for (const skill of skills.active) {
		let content: string;
		try {
			content = await readFile(skill.path, 'utf-8');
		} catch {
			continue;
		}
		const fm = parseDraftFrontmatter(content);
		// Skip hand-authored shims regardless of (missing) source ids.
		if (fm?.skillOrigin === 'shim') {
			result.skipped.push(skill.slug);
			continue;
		}
		// Stale = unparseable frontmatter (the closed blind spot), no source ids
		// to anchor the skill to live knowledge, or no generated_at timestamp
		// (gatherInventory flags missing_generated_at; reconcile must match).
		// Note: updated_after_generation staleness requires a live knowledge
		// lookup (not available here without loading the full store) — those
		// skills are detected by gatherInventory but reconciliation for them
		// is deferred to a future pass that loads the store.
		const stale = !fm || fm.sourceKnowledgeIds.length === 0 || !fm.generatedAt;
		if (!stale) continue;
		result.checked += 1;
		if (options.dryRun) {
			// Report-only: surface the slug without mutating anything.
			result.retired.push(skill.slug);
			continue;
		}
		try {
			const regen = await _internals.regenerateSkill(directory, skill.slug, {
				evaluate: false,
			});
			if (regen.regenerated) {
				result.regenerated.push(skill.slug);
			} else if (regen.retired) {
				// regenerateSkill auto-retired (all source knowledge archived).
				result.retired.push(skill.slug);
			} else {
				// Could not re-derive (no parseable source ids and no slug-token
				// re-cluster match) → retire as the deterministic terminal state.
				const retire = await retireSkill(
					directory,
					skill.slug,
					'stale_no_source_knowledge',
				);
				if (retire.retired) result.retired.push(skill.slug);
			}
		} catch (err) {
			// fail-open: skip this skill, continue the sweep.
			warn(
				`[skill-improver] reconcileStaleActiveSkills: failed to reconcile '${skill.slug}': ${
					err instanceof Error ? err.message : String(err)
				}`,
			);
			result.skipped.push(skill.slug);
		}
	}
	return result;
}

export async function prepareSkillImproverApprovalCandidate(
	req: SkillImproveRequest,
): Promise<SkillImproverApprovalPreparation> {
	const cfg = req.config;
	const now = req.now ?? new Date();
	const targets = (
		req.targets && req.targets.length > 0 ? req.targets : cfg.targets
	) as SkillImproverTarget[];
	const writeMode = req.mode ?? cfg.write_mode;
	const maxCalls = Math.max(
		1,
		Math.min(cfg.max_calls_per_day, req.maxCalls ?? 1),
	);
	const noQuota = {
		date: now.toISOString().slice(0, 10),
		calls_used: 0,
		max_calls: cfg.max_calls_per_day,
	};

	if (!cfg.enabled) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason: 'skill_improver.enabled is false',
				quota: noQuota,
			},
		};
	}
	if (req.signal?.aborted) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason: 'skill_improver aborted',
				quota: noQuota,
			},
		};
	}
	if (!req.sessionId?.trim()) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason:
					'skill_improver requires a session-bound write approval; no sessionId was provided',
				quota: noQuota,
				approvalRequired: {},
			},
		};
	}
	if (req.allowAutoApply === true) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason:
					'skill_improver require_user_approval does not permit auto-apply writes',
				quota: noQuota,
			},
		};
	}

	const delegate =
		req.delegate ??
		createSkillImproverLLMDelegate(req.directory, req.sessionId);
	if (!delegate && !cfg.allow_deterministic_fallback) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason:
					'no_llm_client: skill_improver.allow_deterministic_fallback is false and no OpenCode client is wired. Run from a session where swarmState.opencodeClient is available, or enable allow_deterministic_fallback to use the offline path.',
				quota: noQuota,
			},
		};
	}

	const reservation = await reserveQuota(req.directory, {
		nCalls: maxCalls,
		maxCalls: cfg.max_calls_per_day,
		window: cfg.quota_window,
		now,
	});
	if (!reservation.allowed) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason: reservation.reason ?? 'quota exhausted',
				quota: {
					date: reservation.state.date,
					calls_used: reservation.state.calls_used,
					max_calls: reservation.state.max_calls,
				},
			},
		};
	}

	const releaseReservedQuota = async () => {
		const released = await releaseQuota(req.directory, {
			nCalls: maxCalls,
			maxCalls: cfg.max_calls_per_day,
			window: cfg.quota_window,
			now,
		}).catch(() => ({
			...reservation.state,
			calls_used: Math.max(0, reservation.state.calls_used - maxCalls),
		}));
		return {
			date: released.date,
			calls_used: released.calls_used,
			max_calls: released.max_calls,
		};
	};

	let inventory: InventorySnapshot;
	try {
		throwIfAborted(req.signal);
		inventory = await gatherInventory(req.directory);
		throwIfAborted(req.signal);
	} catch (err) {
		if (isAbortError(err)) {
			return {
				kind: 'result',
				result: {
					ran: false,
					reason: 'skill_improver aborted',
					quota: await releaseReservedQuota(),
				},
			};
		}
		return {
			kind: 'result',
			result: {
				ran: false,
				reason: `inventory_failed: ${err instanceof Error ? err.message : String(err)}`,
				quota: await releaseReservedQuota(),
			},
		};
	}

	let body: string;
	let source: 'llm' | 'deterministic_fallback';
	if (delegate) {
		try {
			throwIfAborted(req.signal);
			body = await delegate(
				buildSystemPrompt(targets, { ...cfg, write_mode: writeMode }),
				buildUserPrompt(inventory),
				req.signal,
			);
			throwIfAborted(req.signal);
			if (!body || body.trim().length === 0) {
				throw new Error('empty LLM response');
			}
			source = 'llm';
		} catch (err) {
			if (isAbortError(err)) {
				return {
					kind: 'result',
					result: {
						ran: false,
						reason: 'skill_improver aborted',
						quota: await releaseReservedQuota(),
					},
				};
			}
			return {
				kind: 'result',
				result: {
					ran: false,
					reason: `llm_call_failed: ${err instanceof Error ? err.message : String(err)}`,
					quota: await releaseReservedQuota(),
				},
			};
		}
	} else {
		try {
			throwIfAborted(req.signal);
		} catch (err) {
			if (isAbortError(err)) {
				return {
					kind: 'result',
					result: {
						ran: false,
						reason: 'skill_improver aborted',
						quota: await releaseReservedQuota(),
					},
				};
			}
			throw err;
		}
		body = '';
		source = 'deterministic_fallback';
	}

	const proposalContent =
		source === 'llm'
			? buildLLMProposalFrame({
					body,
					targets,
					model: cfg.model,
					now,
				})
			: buildDeterministicProposal({
					targets,
					inventory,
					model: cfg.model,
					now,
				});
	const draftWrites: SkillImproverDraftWrite[] = [];
	if (writeMode === 'draft_skills' && inventory.matureCandidates.length > 0) {
		const draftPreview = await generateSkills({
			directory: req.directory,
			mode: 'draft',
			minConfidence: DEFAULT_SKILL_MIN_CONFIDENCE,
			minConfirmations: DEFAULT_SKILL_MIN_CONFIRMATIONS,
			evaluate: req.evaluateDrafts ?? false,
			preview: true,
		});
		for (const written of draftPreview.written) {
			if (typeof written.content !== 'string') {
				return {
					kind: 'result',
					result: {
						ran: false,
						reason:
							'skill_improver draft preview did not return exact candidate content',
						quota: {
							date: reservation.state.date,
							calls_used: reservation.state.calls_used,
							max_calls: reservation.state.max_calls,
						},
					},
				};
			}
			draftWrites.push({
				slug: written.slug,
				path: toApprovalPath(req.directory, written.path),
				content: written.content,
				sourceKnowledgeIds: written.sourceKnowledgeIds,
				...(written.missingSourceKnowledgeIds?.length
					? {
							missingSourceKnowledgeIds: written.missingSourceKnowledgeIds,
						}
					: {}),
			});
		}
	}
	const draftSourceStamps =
		writeMode === 'draft_skills'
			? await buildDraftSourceStampTargets(
					req.directory,
					draftWrites,
					now.toISOString(),
				)
			: [];
	const candidateContent =
		writeMode === 'draft_skills'
			? buildDraftSkillsWriteManifest({
					source,
					model: cfg.model ?? undefined,
					proposalContent,
					drafts: draftWrites,
					draftSourceStamps,
				})
			: proposalContent;
	if (candidateContent.length > MAX_APPROVED_CANDIDATE_CONTENT_CHARS) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason: `skill_improver approval candidate exceeds ${MAX_APPROVED_CANDIDATE_CONTENT_CHARS} characters`,
				quota: {
					date: reservation.state.date,
					calls_used: reservation.state.calls_used,
					max_calls: reservation.state.max_calls,
				},
				source,
				model: cfg.model ?? undefined,
			},
		};
	}
	return buildPreparedApprovalCandidate({
		directory: req.directory,
		now,
		source,
		model: cfg.model ?? undefined,
		proposalContent,
		candidateContent,
		draftWrites,
		draftSourceStamps,
		quota: {
			date: reservation.state.date,
			calls_used: reservation.state.calls_used,
			max_calls: reservation.state.max_calls,
		},
		quotaWindow: cfg.quota_window,
		maxCalls,
		maxCallsPerDay: cfg.max_calls_per_day,
		released: false,
		sessionId: req.sessionId,
	});
}

export async function prepareApprovedSkillImproverCandidateWrite(
	req: SkillImproveRequest,
): Promise<SkillImproverApprovalPreparation> {
	const cfg = req.config;
	const now = req.now ?? new Date();
	const noQuota = {
		date: now.toISOString().slice(0, 10),
		calls_used: 0,
		max_calls: cfg.max_calls_per_day,
	};
	if (!cfg.enabled) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason: 'skill_improver.enabled is false',
				quota: noQuota,
			},
		};
	}
	if (!req.sessionId?.trim()) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason:
					'skill_improver requires a session-bound write approval; no sessionId was provided',
				quota: noQuota,
				approvalRequired: {},
			},
		};
	}
	const candidateContent = req.approvedCandidateContent;
	if (
		!candidateContent ||
		candidateContent.length > MAX_APPROVED_CANDIDATE_CONTENT_CHARS
	) {
		return {
			kind: 'result',
			result: {
				ran: false,
				reason: `skill_improver approved_candidate_content is required and must be <= ${MAX_APPROVED_CANDIDATE_CONTENT_CHARS} characters`,
				quota: noQuota,
			},
		};
	}
	const manifest = parseDraftSkillsWriteManifest(candidateContent);
	const quotaState = await getQuotaState(req.directory, {
		maxCalls: cfg.max_calls_per_day,
		window: cfg.quota_window,
		now,
	});
	return buildPreparedApprovalCandidate({
		directory: req.directory,
		now,
		source:
			manifest?.source ??
			(candidateContent.includes('source: llm')
				? 'llm'
				: 'deterministic_fallback'),
		model: manifest?.model ?? cfg.model ?? undefined,
		proposalContent: manifest?.proposalContent ?? candidateContent,
		candidateContent,
		draftWrites: manifest?.drafts ?? [],
		draftSourceStamps: manifest?.draftSourceStamps ?? [],
		quota: {
			date: quotaState.date,
			calls_used: quotaState.calls_used,
			max_calls: quotaState.max_calls,
		},
		quotaWindow: cfg.quota_window,
		maxCalls: 0,
		maxCallsPerDay: cfg.max_calls_per_day,
		released: true,
		sessionId: req.sessionId,
	});
}

export async function releasePreparedSkillImproverApprovalCandidate(
	prepared: PreparedSkillImproverApprovalCandidate,
): Promise<SkillImproveResult['quota']> {
	if (prepared.maxCalls === 0) {
		return prepared.quota;
	}
	if (prepared.released) {
		return prepared.quota;
	}
	const released = await releaseQuota(prepared.directory, {
		nCalls: prepared.maxCalls,
		maxCalls: prepared.maxCallsPerDay,
		window: prepared.quotaWindow,
		now: prepared.now,
	}).catch(() => ({
		...prepared.quota,
		calls_used: Math.max(0, prepared.quota.calls_used - prepared.maxCalls),
	}));
	prepared.released = true;
	prepared.quota = {
		date: released.date,
		calls_used: released.calls_used,
		max_calls: released.max_calls,
	};
	return prepared.quota;
}

export async function writeApprovedSkillImproverCandidate(
	prepared: PreparedSkillImproverApprovalCandidate,
): Promise<SkillImproveResult> {
	if (prepared.released && prepared.maxCalls > 0) {
		return {
			ran: false,
			reason:
				'skill_improver approval candidate has already been released and cannot be written',
			quota: prepared.quota,
		};
	}
	if (!currentWriteAuthoritySatisfies(prepared.request)) {
		return {
			ran: false,
			reason: 'skill_improver requires an exact human write approval',
			quota: await releasePreparedSkillImproverApprovalCandidate(prepared),
			approvalRequired: {
				request: prepared.request,
				candidateContent: prepared.candidateContent,
				candidateContentChars: prepared.candidateContent.length,
				candidateContentTokenEstimate: estimateTokenCount(
					prepared.candidateContent,
				),
				allowedPaths: prepared.allowedPaths,
			},
			source: prepared.source,
			model: prepared.model,
		};
	}
	const staleStampReason = await preflightDraftSourceStampTargets(
		prepared.draftSourceStamps,
	);
	if (staleStampReason) {
		return {
			ran: false,
			reason: staleStampReason,
			quota: prepared.quota,
		};
	}
	await atomicWrite(prepared.proposalPath, prepared.proposalContent);
	for (const draft of prepared.draftWrites) {
		await atomicWrite(
			resolveApprovedPath(prepared.directory, draft.path),
			draft.content,
		);
	}
	await applyDraftSourceStampTargets(prepared.draftSourceStamps);
	return {
		ran: true,
		proposalPath: prepared.proposalPath,
		source: prepared.source,
		quota: prepared.quota,
		model: prepared.model,
		...(prepared.draftWrites.length > 0
			? {
					draftSkillsWritten: prepared.draftWrites.map((draft) => ({
						slug: draft.slug,
						path: resolveApprovedPath(prepared.directory, draft.path),
						sourceKnowledgeIds: draft.sourceKnowledgeIds,
					})),
				}
			: {}),
	};
}

export async function runSkillImprover(
	req: SkillImproveRequest,
): Promise<SkillImproveResult> {
	const cfg = req.config;
	const now = req.now ?? new Date();
	const targets = (
		req.targets && req.targets.length > 0 ? req.targets : cfg.targets
	) as SkillImproverTarget[];
	const writeMode = req.mode ?? cfg.write_mode;
	const maxCalls = Math.max(
		1,
		Math.min(cfg.max_calls_per_day, req.maxCalls ?? 1),
	);
	const noQuota = {
		date: now.toISOString().slice(0, 10),
		calls_used: 0,
		max_calls: cfg.max_calls_per_day,
	};

	if (!cfg.enabled) {
		return {
			ran: false,
			reason: 'skill_improver.enabled is false',
			quota: noQuota,
		};
	}
	if (req.signal?.aborted) {
		return {
			ran: false,
			reason: 'skill_improver aborted',
			quota: noQuota,
		};
	}
	if (cfg.require_user_approval) {
		const prepared =
			req.approvedCandidateContent !== undefined
				? await prepareApprovedSkillImproverCandidateWrite({
						...req,
						now,
						mode: writeMode,
					})
				: await prepareSkillImproverApprovalCandidate({
						...req,
						now,
						mode: writeMode,
						maxCalls,
						allowAutoApply: req.allowAutoApply === true,
					});
		if (prepared.kind === 'result') {
			return prepared.result;
		}
		if (!currentWriteAuthoritySatisfies(prepared.prepared.request)) {
			return buildApprovalRequiredResult({
				reason: 'skill_improver requires an exact human write approval',
				quota: prepared.prepared.quota,
				prepared: prepared.prepared,
			});
		}
		return await writeApprovedSkillImproverCandidate(prepared.prepared);
	}

	// Resolve the delegate BEFORE touching quota. Pre-flight refusal when
	// no delegate is available and fallback is disabled.
	const delegate =
		req.delegate ??
		createSkillImproverLLMDelegate(req.directory, req.sessionId);
	if (!delegate && !cfg.allow_deterministic_fallback) {
		return {
			ran: false,
			reason:
				'no_llm_client: skill_improver.allow_deterministic_fallback is false and no OpenCode client is wired. Run from a session where swarmState.opencodeClient is available, or enable allow_deterministic_fallback to use the offline path.',
			quota: noQuota,
		};
	}

	const reservation = await reserveQuota(req.directory, {
		nCalls: maxCalls,
		maxCalls: cfg.max_calls_per_day,
		window: cfg.quota_window,
		now,
	});
	if (!reservation.allowed) {
		return {
			ran: false,
			reason: reservation.reason ?? 'quota exhausted',
			quota: {
				date: reservation.state.date,
				calls_used: reservation.state.calls_used,
				max_calls: reservation.state.max_calls,
			},
		};
	}

	let networkStarted = false;
	let sideEffectsStarted = false;
	const reservationQuota = {
		date: reservation.state.date,
		calls_used: reservation.state.calls_used,
		max_calls: reservation.state.max_calls,
	};
	const releaseReservedQuota = async () => {
		const released = await releaseQuota(req.directory, {
			nCalls: maxCalls,
			maxCalls: cfg.max_calls_per_day,
			window: cfg.quota_window,
			now,
		}).catch(() => ({
			...reservation.state,
			calls_used: Math.max(0, reservation.state.calls_used - maxCalls),
		}));
		return {
			date: released.date,
			calls_used: released.calls_used,
			max_calls: released.max_calls,
		};
	};
	const abortResult = async (): Promise<SkillImproveResult> => ({
		ran: false,
		reason: 'skill_improver aborted',
		quota:
			networkStarted || sideEffectsStarted
				? reservationQuota
				: await releaseReservedQuota(),
	});

	let inventory: InventorySnapshot;
	try {
		throwIfAborted(req.signal);
		inventory = await gatherInventory(req.directory);
		throwIfAborted(req.signal);
	} catch (err) {
		if (isAbortError(err)) {
			return await abortResult();
		}
		// Pre-network failure → release the reservation.
		await releaseQuota(req.directory, {
			nCalls: maxCalls,
			maxCalls: cfg.max_calls_per_day,
			window: cfg.quota_window,
			now,
		}).catch(() => {});
		return {
			ran: false,
			reason: `inventory_failed: ${err instanceof Error ? err.message : String(err)}`,
			quota: {
				date: reservation.state.date,
				calls_used: reservation.state.calls_used - maxCalls,
				max_calls: reservation.state.max_calls,
			},
		};
	}

	let body: string;
	let source: 'llm' | 'deterministic_fallback';
	if (delegate) {
		try {
			throwIfAborted(req.signal);
			networkStarted = true;
			body = await delegate(
				buildSystemPrompt(targets, { ...cfg, write_mode: writeMode }),
				buildUserPrompt(inventory),
				req.signal,
			);
			throwIfAborted(req.signal);
			if (!body || body.trim().length === 0) {
				throw new Error('empty LLM response');
			}
			source = 'llm';
		} catch (err) {
			if (isAbortError(err)) {
				return await abortResult();
			}
			// Network I/O began — slot stays consumed (anti-flake policy).
			return {
				ran: false,
				reason: `llm_call_failed: ${err instanceof Error ? err.message : String(err)}`,
				quota: {
					date: reservation.state.date,
					calls_used: reservation.state.calls_used,
					max_calls: reservation.state.max_calls,
				},
			};
		}
	} else {
		// allow_deterministic_fallback === true and no client wired.
		try {
			throwIfAborted(req.signal);
		} catch (err) {
			if (isAbortError(err)) {
				return await abortResult();
			}
			throw err;
		}
		body = '';
		source = 'deterministic_fallback';
	}

	let draftSkillsWritten: SkillImproveResult['draftSkillsWritten'];
	if (writeMode === 'draft_skills' && inventory.matureCandidates.length > 0) {
		try {
			throwIfAborted(req.signal);
		} catch (err) {
			if (isAbortError(err)) {
				return await abortResult();
			}
			throw err;
		}
		sideEffectsStarted = true;
		const gen = await generateSkills({
			directory: req.directory,
			mode: 'draft',
			minConfidence: DEFAULT_SKILL_MIN_CONFIDENCE,
			minConfirmations: DEFAULT_SKILL_MIN_CONFIRMATIONS,
			evaluate: req.evaluateDrafts ?? false,
		});
		draftSkillsWritten = gen.written.map((w) => ({
			slug: w.slug,
			path: w.path,
			sourceKnowledgeIds: w.sourceKnowledgeIds,
		}));
	}
	try {
		throwIfAborted(req.signal);
	} catch (err) {
		if (isAbortError(err)) {
			return await abortResult();
		}
		throw err;
	}

	const proposalDir = path.join(
		req.directory,
		'.swarm',
		'skill-improver',
		'proposals',
	);
	const proposalFile = path.join(proposalDir, `${timestampSlug(now)}.md`);
	const finalBody =
		source === 'llm'
			? buildLLMProposalFrame({
					body,
					targets,
					model: cfg.model,
					now,
				})
			: buildDeterministicProposal({
					targets,
					inventory,
					model: cfg.model,
					now,
				});
	sideEffectsStarted = true;
	await atomicWrite(proposalFile, finalBody);

	// Change 4 (Task 4.3): hardening pass over the unactionable queue. Each LLM
	// attempt is individually quota-gated inside enrichLessonToV3 using the
	// dedicated knowledge-enrichment budget, while this service's own proposal
	// call remains governed by skill_improver.max_calls_per_day. Skipped without
	// a delegate — auto-retiring entries without an attempt would be wrong.
	// Fail-open: a hardening failure never fails the improver run.
	let unactionableHardening: SkillImproveResult['unactionableHardening'];
	if (delegate) {
		unactionableHardening = await hardenUnactionableEntries({
			directory: req.directory,
			llmDelegate: delegate,
			quota: req.enrichmentQuota,
		});
	}

	// Macro reflector (Change 6, Task 5.3): cluster recurring failure motifs from
	// the recent trajectory window and emit skill PROPOSALS (never active skills).
	// Deterministic + read-only over the store; no LLM call, no quota draw.
	// #1821 AC21: `sessionId` is threaded so the dedup-ledger entry's
	// LearningProvenanceV1 write origin records who emitted the proposal.
	const motifResult = await writeMotifProposals(req.directory, {
		...(req.sessionId ? { sessionId: req.sessionId } : {}),
	});
	const macroMotifs = {
		motifs: motifResult.motifs,
		proposalsWritten: motifResult.proposalsWritten.length,
		duplicatesSuppressed: motifResult.duplicatesSuppressed,
	};

	// #1234 Part 4: mine recurring successful tool-sequences and emit
	// workflow-type skill proposals. Same cadence, same proposals dir, no LLM.
	const successMotifResult = await writeSuccessMotifProposals(req.directory, {
		...(req.sessionId ? { sessionId: req.sessionId } : {}),
	});
	const successMotifs = {
		motifs: successMotifResult.motifs,
		proposalsWritten: successMotifResult.proposalsWritten.length,
		duplicatesSuppressed: successMotifResult.duplicatesSuppressed,
	};

	// Issue #1477: self-healing reconciliation of stale active generated skills.
	// Deterministic, no LLM/quota. Only mutates skills when this run is allowed to
	// write skills (draft_skills mode); otherwise reports retire-candidates via a
	// dry run so a proposal-only run never silently rewrites/retires skills.
	const staleSkillReconciliation = await reconcileStaleActiveSkills(
		req.directory,
		{ dryRun: writeMode !== 'draft_skills' },
	);

	// #1234 Part 3D: critic-gated auto-apply of proposals in full-auto mode.
	// Only runs when THIS session is in full-auto AND an LLM delegate is available
	// (the delegate acts as the critic gate). The explicit `req.sessionId` check
	// is load-bearing: hasActiveFullAuto(undefined) scans ALL sessions, so without
	// it a request lacking a sessionId would auto-apply whenever any other session
	// happened to be in full-auto (cross-session leak). Fail-open: never blocks.
	let autoApply: AutoApplyResult | undefined;
	if (
		req.allowAutoApply !== false &&
		delegate &&
		req.sessionId &&
		hasActiveFullAuto(req.sessionId)
	) {
		try {
			autoApply = await autoApplyProposals(req.directory, delegate);
		} catch {
			// fail-open
		}
	}

	return {
		ran: true,
		proposalPath: proposalFile,
		source,
		quota: {
			date: reservation.state.date,
			calls_used: reservation.state.calls_used,
			max_calls: reservation.state.max_calls,
		},
		draftSkillsWritten,
		model: cfg.model ?? undefined,
		unactionableHardening,
		macroMotifs,
		successMotifs,
		staleSkillReconciliation,
		autoApply,
	};
}

export const _internals = {
	runSkillImprover,
	buildDeterministicProposal,
	buildLLMProposalFrame,
	buildSystemPrompt,
	buildUserPrompt,
	buildSkillImproverApprovalRequest,
	gatherInventory,
	reconcileStaleActiveSkills,
	regenerateSkill,
};
