/**
 * Additional macOS sandbox-exec envOverride verification tests.
 *
 * These tests complement the coverage in macos.test.ts by targeting:
 * - Values containing '=' (equals sign) in SBPL double-quoted strings
 * - Cross-platform injection correctness for macOS
 *
 * Platform: macOS only (sandbox-exec is macOS-specific)
 */

import { describe, expect, test } from 'bun:test';

const isMac = process.platform === 'darwin';

import { MacOSSandboxExecutor } from '../../../src/sandbox/macos/sandbox-exec-executor';

// ---------------------------------------------------------------------------
// Supplementary envOverride tests — all skipped on non-macOS
// ---------------------------------------------------------------------------

describe('MacOSSandboxExecutor — envOverride verification (supplementary)', () => {
	// -----------------------------------------------------------------------
	// Equals sign in value — SBPL double-quoted strings treat = as literal
	// -----------------------------------------------------------------------

	test.skipIf(!isMac)(
		'value with embedded equals sign is escaped correctly in SBPL double-quoted string',
		() => {
			const executor = new MacOSSandboxExecutor(['/scope'], '/tmp');
			if (!executor.isAvailable()) return;

			const result = executor.wrapCommand('echo hello', [], undefined, {
				FOO: 'a=b=c',
			});
			// SBPL double-quoted string: backslash-escaped double quotes, not equals
			// The value a=b=c should appear as-is inside the double-quoted SBPL string.
			// We check that the value with embedded = is present in the SBPL setenv line.
			expect(result).toContain('(setenv FOO "a=b=c")');
		},
	);

	test.skipIf(!isMac)(
		'value that is just an equals sign is preserved correctly',
		() => {
			const executor = new MacOSSandboxExecutor(['/scope'], '/tmp');
			if (!executor.isAvailable()) return;

			const result = executor.wrapCommand('echo hello', [], undefined, {
				X: '=',
			});
			expect(result).toContain('(setenv X "=")');
		},
	);

	// -----------------------------------------------------------------------
	// Security: key with shell metacharacters is rejected
	// -----------------------------------------------------------------------

	test.skipIf(!isMac)(
		'key with dollar sign (variable injection) is rejected silently',
		() => {
			const executor = new MacOSSandboxExecutor(['/scope'], '/tmp');
			if (!executor.isAvailable()) return;

			const result = executor.wrapCommand('echo hello', [], undefined, {
				$FOO: 'value',
			});
			// $FOO is not a valid env var name — must not appear in SBPL primitives
			expect(result).not.toContain('$FOO');
			expect(result).not.toContain('(setenv');
			expect(result).not.toContain('(unsetenv');
		},
	);

	test.skipIf(!isMac)(
		'key with parens (SBPL syntax injection) is rejected silently',
		() => {
			const executor = new MacOSSandboxExecutor(['/scope'], '/tmp');
			if (!executor.isAvailable()) return;

			// Attempt to inject SBPL syntax: FOO(BAR) should be rejected
			const result = executor.wrapCommand('echo hello', [], undefined, {
				'FOO(BAR)': 'value',
			});
			expect(result).not.toContain('FOO(BAR)');
			expect(result).not.toContain('(setenv');
		},
	);

	// -----------------------------------------------------------------------
	// Cross-platform injection correctness
	// -----------------------------------------------------------------------

	test.skipIf(!isMac)(
		'setenv SBPL primitive contains the env var name and value verbatim',
		() => {
			const executor = new MacOSSandboxExecutor(['/scope'], '/tmp');
			if (!executor.isAvailable()) return;

			const result = executor.wrapCommand('echo hello', [], undefined, {
				INJECT_ME: 'injected_value',
			});
			// The SBPL profile generated by buildSandboxProfile includes:
			// (setenv INJECT_ME "injected_value")
			// When sandbox-exec parses this profile, INJECT_ME is set to injected_value.
			expect(result).toContain('(setenv INJECT_ME "injected_value")');
		},
	);

	test.skipIf(!isMac)(
		'unsetenv SBPL primitive contains the env var name only (no value)',
		() => {
			const executor = new MacOSSandboxExecutor(['/scope'], '/tmp');
			if (!executor.isAvailable()) return;

			const result = executor.wrapCommand('echo hello', [], undefined, {
				REMOVE_ME: null,
			});
			expect(result).toContain('(unsetenv REMOVE_ME)');
		},
	);

	test.skipIf(!isMac)(
		'mixed valid and invalid keys: valid keys are applied, invalid silently dropped',
		() => {
			const executor = new MacOSSandboxExecutor(['/scope'], '/tmp');
			if (!executor.isAvailable()) return;

			const result = executor.wrapCommand('echo hello', [], undefined, {
				VALID_KEY: 'valid_value',
				'INVALID;KEY': 'should_be_dropped',
				ANOTHER_VALID: 'another_value',
			});
			// Valid keys appear in SBPL
			expect(result).toContain('(setenv VALID_KEY "valid_value")');
			expect(result).toContain('(setenv ANOTHER_VALID "another_value")');
			// Invalid key must not appear
			expect(result).not.toContain('INVALID');
			expect(result).not.toContain('should_be_dropped');
		},
	);
});
