/**
 * Issue #1717 — G8 (eval gate + stub generation) end-to-end tests.
 *
 * Split per AGENTS.md invariant 7 FR-006 (every new test file under 500 lines).
 * G10/G12 tests live in skill-generator-1717-g10-g12.test.ts.
 */

import { afterEach, beforeEach, describe, expect, it, mock } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import {
	activateProposal,
	generateEvalStub,
	writeEvalStub,
} from '../../../src/services/skill-generator';
import {
	cleanupTmp,
	makeCluster,
	makeEntry,
	makeTmp,
	redirectHivePath,
	restoreEnv,
	writeSwarmKnowledge,
} from './_skill-generator-1717-helpers';

let tmp: string;

beforeEach(() => {
	mock.restore();
	tmp = makeTmp();
	redirectHivePath(tmp);
});

afterEach(() => {
	restoreEnv();
	cleanupTmp(tmp);
	mock.restore();
});

// ============================================================================
// G8 — eval stub generation
// ============================================================================

describe('G8: generateEvalStub + writeEvalStub', () => {
	it('derives an eval case from cluster directive fields', () => {
		const cases = generateEvalStub(makeCluster());
		expect(cases).toHaveLength(1);
		expect(cases[0].id).toBe('auto-stub');
		expect(cases[0].required_phrases).toContain('call declare_scope');
		// verification_checks merge into required_phrases
		expect(cases[0].required_phrases).toContain('check scope is declared');
		// Note: forbidden_actions are deliberately NOT mapped to
		// forbidden_phrases (the renderer documents them, which would always
		// false-reject). See generateEvalStub comment in skill-generator.ts.
		expect(cases[0].forbidden_phrases ?? []).toEqual([]);
	});

	it('returns [] when the cluster has no required actions or verification checks', () => {
		// forbidden_actions alone do not produce a stub (see comment above).
		const cases = generateEvalStub(
			makeCluster({
				required_actions: [],
				forbidden_actions: ['something forbidden'],
				verification_checks: [],
			}),
		);
		expect(cases).toEqual([]);
	});

	it('caps phrases at 160 chars (matches MAX_PHRASE_LENGTH)', () => {
		const long = 'x'.repeat(200);
		const cases = generateEvalStub(
			makeCluster({ required_actions: [long], forbidden_actions: [] }),
		);
		expect(cases[0].required_phrases?.[0].length).toBe(160);
	});

	it('writeEvalStub writes auto-stub.json under .swarm/skills/evals/<slug>/', async () => {
		const result = await writeEvalStub(
			tmp,
			'issue-1717-skill',
			generateEvalStub(makeCluster()),
		);
		expect(result.written).toBe(true);
		expect(existsSync(result.path)).toBe(true);
		const parsed = JSON.parse(readFileSync(result.path, 'utf-8'));
		expect(parsed.cases).toHaveLength(1);
		expect(parsed.cases[0].required_phrases).toContain('call declare_scope');
	});

	it('writeEvalStub returns {written:false} when there are no directive fields', async () => {
		const result = await writeEvalStub(tmp, 'empty-skill', []);
		expect(result.written).toBe(false);
		expect(result.reason).toBe('no directive fields');
	});
});

// ============================================================================
// G8 — activateProposal unevaluated gate
// ============================================================================

describe('G8: activateProposal unevaluated confirmation gate', () => {
	async function writeProposal(slug: string): Promise<string> {
		const proposalPath = path.join(
			tmp,
			'.swarm',
			'skills',
			'proposals',
			`${slug}.md`,
		);
		await mkdir(path.dirname(proposalPath), { recursive: true });
		await writeFile(
			proposalPath,
			[
				'---',
				`name: ${slug}`,
				'generated_at: 2026-01-01T00:00:00Z',
				'generated_from_knowledge:',
				'  - src-1',
				'source_knowledge_ids:',
				'  - src-1',
				'status: draft',
				'---',
				'<!-- generated by opencode-swarm skill-generator. Do not edit by hand. -->',
				'',
				`# ${slug}`,
				'',
				'## Required Procedure',
				'- call declare_scope',
				'',
				'## Forbidden Shortcuts',
				'- skip scope declaration',
				'',
			].join('\n'),
			'utf-8',
		);
		return proposalPath;
	}

	beforeEach(async () => {
		// Seed a source entry so stamping works post-activation.
		await writeSwarmKnowledge(tmp, [makeEntry('src-1')]);
	});

	it('blocks activation when evaluate:true, no eval set, confirmUnevaluated:false', async () => {
		await writeProposal('uneval-skill');
		// No eval fixtures on disk → evaluateSkillChange returns unevaluated.
		// No stub written either (we did not call generateSkills), so the gate
		// returns 'unevaluated' and activation is blocked.
		const result = await activateProposal(tmp, 'uneval-skill', false, {
			evaluate: true,
			confirmUnevaluated: false,
		});
		expect(result.activated).toBe(false);
		expect(result.reason).toContain('unevaluated');
		expect(result.evaluation?.status).toBe('unevaluated');
		// No active SKILL.md written.
		expect(
			existsSync(
				path.join(
					tmp,
					'.opencode',
					'skills',
					'generated',
					'uneval-skill',
					'SKILL.md',
				),
			),
		).toBe(false);
	});

	it('allows activation when confirmUnevaluated:true', async () => {
		await writeProposal('confirmed-skill');
		const result = await activateProposal(tmp, 'confirmed-skill', false, {
			evaluate: true,
			confirmUnevaluated: true,
		});
		expect(result.activated).toBe(true);
		expect(result.evaluation?.status).toBe('unevaluated');
	});

	it('does not fire the gate when evaluate is false (default)', async () => {
		await writeProposal('no-eval-skill');
		const result = await activateProposal(tmp, 'no-eval-skill', false, {
			evaluate: false,
		});
		expect(result.activated).toBe(true);
	});

	it('end-to-end: stub makes the gate return passed (directive-backed proposal)', async () => {
		await writeProposal('stubbed-skill');
		// Write the auto-stub the way generateSkills would. The proposal body
		// above includes 'call declare_scope' (required) and 'skip scope
		// declaration' (forbidden) but NOT the verification check 'check scope
		// is declared' — so the stub's required_phrases (which include the
		// verification check) will find it missing. We write a stub derived
		// from a cluster that ONLY has the required_action + forbidden_action
		// (no verification_check) so the proposal matches.
		await writeEvalStub(
			tmp,
			'stubbed-skill',
			generateEvalStub(
				makeCluster({
					slug: 'stubbed-skill',
					verification_checks: [],
				}),
			),
		);
		const result = await activateProposal(tmp, 'stubbed-skill', false, {
			evaluate: true,
			confirmUnevaluated: false,
		});
		expect(result.activated).toBe(true);
		expect(result.evaluation?.status).toBe('passed');
	});

	it('negative: stub REJECTS when a required phrase is missing from the proposal', async () => {
		// Proposal body has 'call declare_scope' but the stub also demands
		// 'check scope is declared' (the verification_check), which the
		// proposal omits → the gate must reject.
		await writeProposal('reject-skill');
		await writeEvalStub(
			tmp,
			'reject-skill',
			generateEvalStub(makeCluster({ slug: 'reject-skill' })),
		);
		const result = await activateProposal(tmp, 'reject-skill', false, {
			evaluate: true,
			confirmUnevaluated: false,
		});
		expect(result.activated).toBe(false);
		expect(result.evaluation?.status).toBe('rejected');
		expect(result.evaluation?.passed).toBe(false);
		expect(result.reason).toContain('validation_failed');
	});

	it('long-directive: 250-char required_action does not false-reject', async () => {
		const longDirective = 'call '.concat('x'.repeat(245)); // 249 chars total
		// Write a proposal that contains the full long directive.
		const proposalPath = path.join(
			tmp,
			'.swarm',
			'skills',
			'proposals',
			'long-dir-skill.md',
		);
		await mkdir(path.dirname(proposalPath), { recursive: true });
		await writeFile(
			proposalPath,
			[
				'---',
				'name: long-dir-skill',
				'generated_from_knowledge:',
				'  - src-1',
				'source_knowledge_ids:',
				'  - src-1',
				'status: draft',
				'---',
				'<!-- generated by opencode-swarm skill-generator. Do not edit by hand. -->',
				'',
				'# long-dir-skill',
				'',
				'## Required Procedure',
				`- ${longDirective}`,
				'',
				'## Forbidden Shortcuts',
				'- none',
				'',
			].join('\n'),
			'utf-8',
		);
		// Stub truncates to 160 chars; the proposal has the full 249-char
		// directive. includesPhrase (substring) matches because the 160-char
		// stub phrase is a prefix of the rendered directive.
		await writeEvalStub(
			tmp,
			'long-dir-skill',
			generateEvalStub(
				makeCluster({
					slug: 'long-dir-skill',
					required_actions: [longDirective],
					forbidden_actions: [],
					verification_checks: [],
				}),
			),
		);
		const result = await activateProposal(tmp, 'long-dir-skill', false, {
			evaluate: true,
			confirmUnevaluated: false,
		});
		expect(result.activated).toBe(true);
		expect(result.evaluation?.status).toBe('passed');
	});
});
